# Generated by Django 4.2.11 on 2024-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Toys', 'Toys'), ('Home', 'Home'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion')], default='Fashion', max_length=64)),
            ],
        ),
    ]
